# Generated by Django 6.1.2 on 2026-10-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaijiaoTopicSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('topic_id', models.CharField(max_length=32, unique=True, verbose_name='帖子 ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('node_name', models.CharField(blank=True, default='', max_length=64, verbose_name='板块')),
                ('category', models.CharField(blank=True, default='', max_length=64, verbose_name='分类（板块，无板块时取首个标签）')),
                ('cover', models.CharField(blank=True, default='', max_length=512, verbose_name='封面（源站原始地址）')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='阅读数')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('source_page', models.PositiveIntegerField(default=0, verbose_name='来源页码')),
                ('translations', models.JSONField(blank=True, default=dict, verbose_name='各语言译文')),
            ],
            options={
                'verbose_name': '海角帖子快照',
                'verbose_name_plural': '海角帖子快照',
                'db_table': 'haijiao_topic_snapshot',
                'ordering': ['-id'],
            },
        ),
    ]
