# Generated by Django 6.1.2 on 2026-10-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaijiaoRankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.CharField(max_length=16, verbose_name='榜单维度')),
                ('period', models.CharField(max_length=16, verbose_name='周期')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='总人数')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='榜单条目')),
            ],
            options={
                'verbose_name': '海角排行榜快照',
                'verbose_name_plural': '海角排行榜快照',
                'db_table': 'haijiao_ranking_snapshot',
                'ordering': ['board', 'period'],
                'unique_together': {('board', 'period')},
            },
        ),
    ]
