# Generated by Django 6.1.2 on 2026-10-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_haijiaorankingsnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HaijiaoRankingSnapshot',
        ),
    ]
